
fos_rest:
  param_fetcher_listener: true
  disable_csrf_role: ROLE_USER

  body_listener:
    enabled: true
    throw_exception_on_unsupported_content_type: true

  view:
    view_response_listener: true

  format_listener:

    rules:

      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }

      - { path: ^/, stop: true}