security:

    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
         app_user_provider:
             entity:
                class: App\Entity\User
                property: email

    role_hierarchy:
      ROLE_ADMIN: [ ROLE_ADMIN , ROLE_MODERATOR, ROLE_USER]
      ROLE_MODERATOR: [ROLE_MODERATOR, ROLE_USER]
      ROLE_USER : [ROLE_USER]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider : app_user_provider


            form_login:
                login_path: login_path
                check_path: login_path
                enable_csrf : true

            logout:
                path : logout
                target : home

    access_control:
         - { path: ^/admin/*, roles: ROLE_ADMIN }
         - { path: ^/moderator/*, roles : ROLE_MODERATOR}
         - { path: ^/reviews/create, roles: ROLE_USER }
         - { path: ^/reviews/\d+/edit, roles: ROLE_USER }
         - { path: ^/books/create, roles: ROLE_USER }


