security:

    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
         app_user_provider:
             entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider : app_user_provider


            form_login:
                login_path: login_path
                check_path: login_path
                enable_csrf : true

            logout:
                path : logout
                target : home

    access_control:
         - { path: ^/admin/*, roles: ROLE_ADMIN }
         - { path: ^/reviews/user-reviews, roles: ROLE_USER }
